"""Bar 1 (docs/SPEC.md S4) for iteration 3: the constraint engine is correct.

Correct here has a specific, checkable meaning. hpaanalyzer/kubeversion.py is
a port of github.com/Masterminds/semver/v3 v3.3.0 - the exact version helm
v3.16.4 pins - wrapped in the five lines of
helm/pkg/chartutil/compatible.go:IsCompatibleRange. "Correct" therefore means
"answers what helm would answer", not "answers what its author expected".

So the bulk of this suite asserts nothing of my own devising. It replays
tests/oracle_semver.json, which holds 2632 (constraint, version, answer)
triples produced by BUILDING the real Go library and asking it. That file is
regenerated by `python3 proof/p3_oracle.py --freeze`, which refuses to write
unless the live comparison passes first. The tests here need no Go toolchain
and no network, so the conformance claim survives in CI.

The hand-written cases that follow the replay are not a second opinion on
semver semantics; they cover the layer ABOVE it - declared_range()'s job of
turning a constraint into a set of Kubernetes minors, and its three honest
states (undeclared / unparseable / parsed).
"""

import json
import os
import unittest

from hpaanalyzer import kubeversion as kv

ORACLE = os.path.join(os.path.dirname(__file__), "oracle_semver.json")


class TestConformanceToTheRealLibrary(unittest.TestCase):
    """Every pair the Go oracle answered, replayed against the port."""

    @classmethod
    def setUpClass(cls):
        with open(ORACLE, encoding="utf-8") as f:
            cls.table = json.load(f)

    def _ours(self, constraint, version):
        """The port, through helm's IsCompatibleRange shape.

        IsCompatibleRange returns FALSE - not an error, not True - when either
        side fails to parse. Reproducing that here matters: it is the reason a
        typo'd kubeVersion makes a chart uninstallable rather than unchecked.
        """
        try:
            con = kv.parse_constraint(constraint)
        except kv.ConstraintError:
            return False
        return con.check(version)

    def test_oracle_table_is_the_pinned_versions(self):
        self.assertEqual(self.table["semver_version"], "v3.3.0")
        self.assertEqual(self.table["helm_version"], "v3.16.4")

    def test_oracle_table_is_not_trivially_small(self):
        # A suite that silently degrades to 3 cases proves nothing. If the
        # frozen table ever shrinks, that is a defect in the freeze, and it
        # should fail here rather than pass quietly.
        self.assertGreater(len(self.table["cases"]), 2000)

    def test_every_frozen_pair_agrees(self):
        disagreements = []
        for constraint, version, expected in self.table["cases"]:
            got = self._ours(constraint, version)
            if got != expected:
                disagreements.append((constraint, version, expected, got))
        self.assertEqual(
            disagreements, [],
            f"{len(disagreements)} of {len(self.table['cases'])} pairs "
            f"disagree with Masterminds/semver v3.3.0; first few: "
            f"{disagreements[:5]}")

    def test_the_table_actually_contains_both_answers(self):
        # Guards against a degenerate oracle: if every frozen answer were
        # False, a port that returned False unconditionally would pass the
        # test above.
        answers = {c[2] for c in self.table["cases"]}
        self.assertEqual(answers, {True, False})


class TestThePrereleaseRule(unittest.TestCase):
    """The single most surprising behaviour, pinned in isolation.

    Managed distributions report gitVersions that are SemVer PRERELEASES
    (v1.29.3-gke.1093000, v1.30.0-eks-a5ec690, v1.28.9-aks1). Masterminds
    excludes prerelease versions from any constraint whose comparators carry
    no prerelease part. The consequence is not subtle: `>=1.29.0` matches no
    GKE cluster at any version.
    """

    def check(self, c, v):
        return kv.parse_constraint(c).check(v)

    def test_plain_lower_bound_rejects_managed_versions(self):
        for v in ("1.29.3-gke.1093000", "1.30.0-eks-a5ec690", "1.28.9-aks1"):
            self.assertFalse(self.check(">=1.28.0", v), v)

    def test_plain_lower_bound_still_accepts_plain_versions(self):
        self.assertTrue(self.check(">=1.28.0", "1.30.0"))

    def test_zero_suffix_admits_managed_versions(self):
        for v in ("1.29.3-gke.1093000", "1.30.0-eks-a5ec690", "1.28.9-aks1"):
            self.assertTrue(self.check(">=1.28.0-0", v), v)


class TestDeclaredRangeStates(unittest.TestCase):
    """declared_range() has three states and must not blur them.

    The blur is the dangerous part: reporting "unknown" for a constraint that
    actually parses to the empty set, or "fine" for one that does not parse,
    both turn a fact into a shrug.
    """

    def test_absent_is_not_declared(self):
        for raw in (None, "", "   "):
            r = kv.declared_range(raw)
            self.assertFalse(r.declared, repr(raw))
            self.assertFalse(r.known, repr(raw))
            self.assertIsNone(r.error, repr(raw))

    def test_unparseable_is_declared_but_not_parsed_and_carries_the_error(self):
        r = kv.declared_range(">=1.24 and <1.26")
        self.assertTrue(r.declared)
        self.assertFalse(r.parsed)
        self.assertFalse(r.known)
        self.assertTrue(r.error)

    def test_parsed_but_empty_is_distinct_from_unparseable(self):
        r = kv.declared_range(">=1.30.0-0 <1.20.0-0")
        self.assertTrue(r.parsed)      # the string is valid syntax
        self.assertIsNone(r.error)
        self.assertEqual(r.minors, ())  # and satisfied by nothing
        self.assertFalse(r.known)

    def test_parsed_range_is_the_right_set(self):
        r = kv.declared_range(">=1.20.0-0 <1.22.0-0")
        self.assertTrue(r.known)
        self.assertEqual(r.minors, ((1, 20), (1, 21)))
        self.assertEqual(r.floor, (1, 20))
        self.assertEqual(r.ceiling, (1, 21))
        self.assertEqual(r.describe(), "1.20-1.21")
        self.assertFalse(r.truncated)


class TestDeclaredRangeSampling(unittest.TestCase):
    """The set is sampled, and the sampling has to be defensible."""

    def test_open_ended_range_is_marked_truncated(self):
        # ">=1.30.0-0" admits every future minor. Reporting a ceiling of
        # 1.60 as if it were the chart's own upper bound would be a fabricated
        # fact; `truncated` is how the sampling admits its own edge.
        r = kv.declared_range(">=1.30.0-0")
        self.assertTrue(r.truncated)
        self.assertTrue(r.describe().endswith("+"))
        self.assertEqual(r.ceiling, (1, kv.DOMAIN_MAX_MINOR))

    def test_closed_range_is_not_marked_truncated(self):
        self.assertFalse(kv.declared_range(">=1.20.0-0 <1.25.0-0").truncated)

    def test_a_minor_counts_if_any_patch_in_it_qualifies(self):
        # `>=1.21.3` excludes 1.21.0 but includes 1.21.9, so 1.21 IS in the
        # supported set. Probing only x.y.0 would drop the whole minor.
        r = kv.declared_range(">=1.21.3-0 <1.23.0-0")
        self.assertIn((1, 21), r.minors)
        self.assertIn((1, 22), r.minors)
        self.assertNotIn((1, 20), r.minors)

    def test_accepts_prerelease_is_measured_not_pattern_matched(self):
        self.assertFalse(kv.declared_range(">=1.29.0").accepts_prerelease)
        self.assertTrue(kv.declared_range(">=1.29.0-0").accepts_prerelease)
        # A wildcard carries no prerelease comparator either, but Masterminds
        # treats `*` specially. Whatever it does, we report what it does -
        # which is the point of asking the engine instead of grepping for
        # "-0".
        self.assertEqual(kv.declared_range("*").accepts_prerelease,
                         kv.parse_constraint("*").check("1.30.3-gke.1093000"))


class TestRangeQueries(unittest.TestCase):
    """The three queries the severity logic is built out of."""

    def setUp(self):
        self.r = kv.declared_range(">=1.23.0-0 <1.28.0-0")

    def test_below_and_at_or_above_partition_the_set(self):
        below = self.r.below(1, 25)
        above = self.r.at_or_above(1, 25)
        self.assertEqual(below, [(1, 23), (1, 24)])
        self.assertEqual(above, [(1, 25), (1, 26), (1, 27)])
        self.assertEqual(sorted(below + above), list(self.r.minors))

    def test_boundary_minor_is_at_or_above_not_below(self):
        # An API removed in 1.25 is gone AS OF 1.25. Putting the boundary
        # minor on the wrong side is an off-by-one that downgrades a real
        # outage to a portability note.
        self.assertIn((1, 25), self.r.at_or_above(1, 25))
        self.assertNotIn((1, 25), self.r.below(1, 25))

    def test_includes(self):
        self.assertTrue(self.r.includes(1, 23))
        self.assertFalse(self.r.includes(1, 28))


class TestParseVersionEdges(unittest.TestCase):
    """Version strings the tool will actually be handed."""

    def test_v_prefix_is_accepted(self):
        self.assertIsNotNone(kv.parse_version("v1.29.3"))

    def test_partial_versions_are_accepted(self):
        for text in ("1", "1.29", "1.29.3"):
            self.assertIsNotNone(kv.parse_version(text), text)

    def test_junk_is_none_not_an_exception(self):
        for text in ("", "unknown", "1.2.3.4", "v", "latest"):
            self.assertIsNone(kv.parse_version(text), text)


if __name__ == "__main__":
    unittest.main()
