#!/usr/bin/env python3
"""PROOF R1-Bar2: the pod-QoS finding was correct and invisible.

Iteration 1 made pod QoS arithmetically correct (proof/p1_qos.py: OLD 5/8
wrong -> NEW 0/8 wrong). That is SPEC S4 Bar 1. This script tests Bar 2:
does a real defect of this class reach the TERMINAL fix-first list?

Method: build one chart whose only flaw is a resource-less init container in
a pod whose app container is Guaranteed. Run the real engine twice --

  BEFORE: RS015 emitted at MEDIUM (the severity shipped by the first cut of
          iteration 1). Reproduced by patching the Severity back at runtime,
          so this is the live code path, not a recollection.
  AFTER : RS015 emitted at HIGH (current source).

and print what the terminal actually shows in each case. No assertion about
the fix-first list is made by hand; the summary is generated by the real
report.stdout_summary and searched.
"""

import os
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

from hpaanalyzer import checks_workload                    # noqa: E402
from hpaanalyzer.engine import analyze                     # noqa: E402
from hpaanalyzer.models import Severity                    # noqa: E402
from hpaanalyzer.report import stdout_summary              # noqa: E402

CHART = {
    "Chart.yaml": "apiVersion: v2\nname: fit\nversion: 1.0.0\n"
                  "appVersion: \"1.0.0\"\n",
    "values.yaml": "replicaCount: 3\n",
    "templates/deployment.yaml": """apiVersion: apps/v1
kind: Deployment
metadata:
  name: fit
  labels:
    app.kubernetes.io/name: fit
    app.kubernetes.io/instance: fit
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  template:
    metadata:
      labels: {app.kubernetes.io/name: fit}
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ["sh", "-c", "sleep 1"]
      containers:
        - name: app
          image: eclipse-temurin:17.0.10_7-jre-jammy
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=70.0"
          resources:
            requests: {cpu: "1", memory: "2Gi"}
            limits: {cpu: "1", memory: "2Gi"}
          readinessProbe:
            httpGet: {path: /health/ready, port: 8080}
          livenessProbe:
            httpGet: {path: /health/live, port: 8080}
            initialDelaySeconds: 60
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
""",
}


def build():
    d = tempfile.mkdtemp(prefix="p1b-")
    os.makedirs(os.path.join(d, "templates"))
    for rel, body in CHART.items():
        with open(os.path.join(d, rel), "w") as f:
            f.write(body)
    return d


def run(chart, force_medium):
    """Return (severity_of_RS015, terminal_summary)."""
    real_add = checks_workload._add

    def patched(result, **kw):
        if force_medium and kw.get("rule_id") == "RS015":
            kw["severity"] = Severity.MEDIUM
        return real_add(result, **kw)

    checks_workload._add = patched
    try:
        result = analyze(chart, helm_mode="off")
    finally:
        checks_workload._add = real_add
    hit = [f for f in result.findings if f.rule_id == "RS015"]
    sev = hit[0].severity.label if hit else "(not emitted)"
    return sev, stdout_summary(result, "/tmp/r.txt")


def main():
    chart = build()
    print(__doc__)
    print("The chart under test: app container request == limit for cpu and")
    print("memory (the author asked for Guaranteed); one init container")
    print("'wait-for-db' with no resources. Upstream ComputePodQOS iterates")
    print("ALL InitContainers unfiltered, so the pod is Burstable.")
    print("Verified against kubernetes/pkg/apis/core/v1/helper/qos/qos.go:")
    print("    for _, c := range pod.Spec.InitContainers { ... yield(&c) ... }")
    print("(no restartPolicy filter -- a one-shot init container demotes the")
    print(" pod's QoS for the pod's entire lifetime).\n")

    failures = 0
    for label, force_medium in (("BEFORE (RS015 = MEDIUM)", True),
                                ("AFTER  (RS015 = HIGH)", False)):
        sev, summary = run(chart, force_medium)
        visible = "RS015" in summary
        print("=" * 72)
        print(f"{label}   emitted severity: {sev}")
        print("=" * 72)
        print(summary)
        print(f"\n  --> RS015 in the terminal fix-first list? "
              f"{'YES' if visible else 'NO'}")
        print(f"  --> SPEC S4 Bar 2: {'PASS' if visible else 'FAIL'}\n")
        if force_medium and visible:
            failures += 1       # the defect we claim to have found isn't there
        if not force_medium and not visible:
            failures += 1       # the fix did not work

    print("=" * 72)
    if failures:
        print(f"PROOF INVALID: {failures} expectation(s) not met.")
        return 1
    print("PROVEN: the finding was emitted correctly and printed nowhere the")
    print("user looks. Bar 1 passed while Bar 2 failed. Raising the severity")
    print("is legitimate only because RS015 cannot fire unless a container")
    print("already has request == limit -- see the guard test in")
    print("tests/test_fitness_qos.py::test_severity_is_justified_by_the_guard.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
